name: iOS CI - WeatherForecast

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint || echo "SwiftLint already installed"

      - name: Run SwiftLint
        run: swiftlint || true

      - name: Build
        run: xcodebuild build -workspace WeatherForecast.xcworkspace -scheme WeatherForecast -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty

      - name: Run tests and collect coverage
        run: codebuild test -workspace WeatherForecast.xcworkspace -scheme WeatherForecast -destination 'platform=iOS Simulator,name=iPhone 14' -enableCodeCoverage YES | xcpretty
          set -o pipefail
          xcodebuild test -workspace WeatherForecast.xcodeproj -scheme WeatherForecast -destination 'platform=iOS Simulator,name=iPhone 14' -enableCodeCoverage YES | xcpretty
